name: "ShitOS"
id: ShitOS
vibversion: 0.8.1

stages:
- id: build
  base: ghcr.io/vanilla-os/nvidia-exp:main
  singlelayer: false
  labels:
    maintainer: Tri Phuong Nguyen
  args:
    DEBIAN_FRONTEND: noninteractive
  
  runs:
    commands:
      - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends

  modules:
  - name: init-setup
    type: shell
    commands:
      - lpkg --unlock
      - apt-get update

  # ACTIONS START

  - name: download debs
    type: shell
    commands:
      - wget -P /deb-pkgs "https://download.opensuse.org/repositories/home:/lamlng/Debian_Unstable/amd64/ibus-bamboo_0.8.4-0_amd64.deb"
      - wget -P /deb-pkgs "https://github.com/Alex313031/thorium/releases/download/M130.0.6723.174/thorium-browser_130.0.6723.174_AVX2.deb"
      # Discord should be installed in container, not host.
      # RPC applications will be installed alongside it.
      # - wget -P /deb-pkgs "https://github.com/Vencord/Vesktop/releases/download/v1.5.8/vesktop_1.5.8_amd64.deb"

  - name: essential packages
    type: apt
    source:
      packages:
        - build-essential
        - libxml2-dev
        - libpcre2-dev
        - libfast-float-dev
        - libicu-dev
        - valac
        - neovim
        - curl
        - wget
        - ibus
        - git
        - gpg
        - xdg-desktop-portal-gnome
        - xdg-desktop-portal-gtk
        - nvidia-settings
        - mesa-utils
        - vulkan-tools
        - kitty
        - software-properties-common


  - name: nvidia-container-toolkit
    type: shell
    commands:
      - curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
      - curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
      - apt-get update
      - apt-get install -y nvidia-container-toolkit=1.17.8-1 nvidia-container-toolkit-base=1.17.8-1 libnvidia-container-tools=1.17.8-1 libnvidia-container1=1.17.8-1

  - name: vte-sixel
    type: shell
    commands:
      - cd /build
      - git clone https://gitlab.gnome.org/GNOME/vte --depth 1
      - meson _build -Dsixel=true
      - ninja -C _build
      - ninja -C _build install
      - apt-get purge valac
      - rm -rf /build

  - name: custom deb files
    type: includes
    includes:
      - modules/50-install-debs.yml

  # ACTIONS END

  - name: set-image-name-abroot
    type: includes
    includes:
      - modules/80-set-image-abroot-config.yml

  - name: cleanup
    type: shell
    commands:
      - apt-get autoremove -y
      - apt-get clean
      - lpkg --lock

  - name: fsguard
    type: fsguard
    CustomFsGuard: false
    FsGuardLocation: "/usr/sbin/FsGuard"
    GenerateKey: true
    FilelistPaths: ["/usr/bin"]
    modules:
      - name: remove-prev-fsguard
        type: shell
        commands:
          - rm -rf /FsGuard 
          - rm -f ./minisign.pub ./minisign.key 
          - chmod +x /usr/sbin/init

  - name: cleanup2
    type: shell
    commands:
      - rm -rf /tmp/*
      - rm -rf /var/tmp/*
      - rm -rf /sources
